### ISSUE TITLE
About Flow module

### ISSUE THREAD

**Issue by ehabhelmy82** [shaohua0116/Multiview2Novelview#10]
Dear Author
Thank you for sharing your code
I have a question about flow module using appearance flow network, in [23] they reported that they used Disocclusionaware Appearance Flow Network, Did you used DOAFN or just AFN?
Thanks

**Comment by shaohua0116** [comment]
Our flow module is similar to AFN except that the architecture is fully-convolutional (i.e. without FC layers). We do not use DOAFN because it requires 3D supervision (e.g. surface normal), which makes it hard to apply to real-world scenes.

**Comment by ehabhelmy82** [comment]
Thank you very much for your reply.
One more question, on what basis do you choose the number of iterations used for each data set, for example i noticed that you trained your model as follow:
Synthia, model_checkpoint_path: "model-33001"
Car model_checkpoint_path: "model-140001"
Chair model_checkpoint_path: "model-180001"
KITTI model_checkpoint_path: "model-41001"
Why you stopped kitti at 41001 and car at 180001?
Thanks again

**Comment by ehabhelmy82** [comment]
???

**Comment by shaohua0116** [comment]
It takes longer to train models for cars and chairs, partially because we train those model using four source views.

**Comment by ehabhelmy82** [comment]
I understand this point but my question why you stopped at model 33001 for synthia not 70001 for example?
on what basis do you decide to terminate training at a certain model? why this model specially and why not the same for all data sets?

**Comment by shaohua0116** [comment]
I stopped the models once the training curves on TensorBoard converge. 
Why not looking at validation sets? The main reason is that given the training set is extremely large (considering all the permutations of multiple source/target views), it is less likely a model can simply overfit. Also, I follow the training and test splits proposed in prior work, where no validation sets were provided.

**Comment by ehabhelmy82** [comment]
Many thanks 
Can you kindly give me the command you used to monitor training curve?

**Comment by shaohua0116** [comment]
You can host [TensorBoard](https://www.tensorflow.org/guide/summaries_and_tensorboard) under `./train_dir` (using `tensorboard --logdir . --port 6006`) and then you should be able to see [this](https://github.com/shaohua0116/Multiview2Novelview/#interpret-tensorboard) under the IMAGES tab and losses under the SCALARS tab.
