### ISSUE TITLE
Evaluate model from checkpoints

### ISSUE THREAD

**Issue by kanybekasanbekov** [shaohua0116/Multiview2Novelview#14]
Hello,
I am trying to evaluate model from checkpoints provided by you.
I have referred to descriptions provided by you in Github.
Thus I used 
_**python evaler.py --dataset kitti --data_id_list ./testing_tuple_lists/id_kitti.txt --checkpoint ./kitti_checkpoint/model-1 --loss True --write_summary True --summary_file log_kitti.txt --plot_image True --output_dir img_kitti**_ .
However, I get an error: **_OutOfRangeError (see above for traceback): Read less bytes than requested_**

I would appreciate if anyone could help me.

**Comment by liustu** [comment]
do you do training on dataset of car? I have some questions during test.

**Comment by kanybekasanbekov** [comment]
Hey, I did not do training on cars

**Comment by liustu** [comment]
Ok,thank you.&nbsp;



---Original---
