### ISSUE TITLE
Sharing the scripts to make hdf5 file for custom dataset

### ISSUE THREAD

**Issue by phongnhhn92** [shaohua0116/Multiview2Novelview#2]
Hello sirs,
I am trying to implement your code with my own small dataset.
Is that okay if you can share how you create the dataset in case of ShapeNet or KITTI.

**Comment by shaohua0116** [comment]
I created the datasets with IPython and I'm afraid I don't have the command history now. But creating a dataset could be done by following the following instructions.

Train and test your own datasets:* Create a directory
```bash
$ mkdir ./datasets/YOUR_DATASET
```
* Store your data as an h5py file datasets/YOUR_DATASET/data.hy and each data point contains
    * 'image': has shape [h, w, c], where c is the number of channels (grayscale images: 1, color images: 3)
    * 'pose': represented as an one-hot vector of a vector representing a 6DoF camera pose
* Maintain a list datasets/YOUR_DATASET/id.txt listing ids of all data points and split the list into train.txt and test.txt
* Modify trainer.py including args, data_info, etc.
* Implement a data loader like `./datasets/shapenet_car.py` and it under `./datasets/`
* Finally, train and test models:
```bash
$ python trainer.py --dataset YOUR_DATASET
$ python evaler.py --dataset YOUR_DATASET

**Comment by phongnhhn92** [comment]
@shaohua0116 Thanks for your kind explanation ! I understand it now. But I have a few questions when I didn't understand reading your paper. 
1. When I checked the data inside the h5py file of KITTI dataset and ShapeNet dataset. I found that for each key image in the KITTI dataset, there are 3 inner key information: image, pose, and pose_matrix. But the in ShapeNet dataset, there are only 2 inner key information: image and pose. Can u explain why you need pose_matrix to train ?
2. My second question is that: in case of KITTI dataset. I can see that pose is a vector representing 6DoF and pose_matrix is a 3x4 matrix. Would you mind telling me how did you obtain those values from KITTI dataset. I checked the guideline at this link https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_raw_data.zip and it said that I can get poses from GPS/IMU data. So I would like to ask is that the way you get those pose information ? 
Thank you in advance !

**Comment by shaohua0116** [comment]
Only the “pose” is used for training and testing. Each 6DoF pose vector in my KITTI dataset consists of a translation vector (x, y, z) and rotation. Pose vectors can be computed from pose 3x4 matrix, which is provided in the original KITTI dataset.

**Comment by phongnhhn92** [comment]
Thank you for your help ! I will try as your suggestion.
