### ISSUE TITLE
load kitti checkpoint failed

### ISSUE THREAD

**Issue by buaaduke** [shaohua0116/Multiview2Novelview#3]
Hi,
I am trying to train your network using my own dataset. I want to finetune the model from your pretrained kitti checkpint, but it failed.

**Comment by shaohua0116** [comment]
Can you share the command that you used?

**Comment by buaaduke** [comment]
python trainer.py  --batch_size 4 --dataset kitti --num_input 4 --checkpoint ～/kitti_checkpoint/model-1.data-00000-of-00001

**Comment by shaohua0116** [comment]
Please use the following command:
```bash
python trainer.py --batch_size 4 --dataset kitti --num_input 4 --checkpoint ～/kitti_checkpoint/model-1
```

**Comment by buaaduke** [comment]
It works, thank you.
