### ISSUE TITLE
Foreground Mask

### ISSUE THREAD

**Issue by AmirMahdiNassiri** [shaohua0116/Multiview2Novelview#8]
Hello dear authors,

In your dataset files (e.g. shapenet_car.py), a foreground mask is also concatenated to the image tensor. Can I know what is the purpose of it? Unfortunately, I can not find where it is used. 

Is it related to calculating the loss? Maybe opting out the background pixels and only calculating loss on the object's pixels?

Any information is greatly appreciated.
Thanks.

![foreground mask](https://user-images.githubusercontent.com/45865860/55834408-7776ec00-5adf-11e9-8879-007b87f2c719.png)

**Comment by shaohua0116** [comment]
Please just ignore the foreground mask. I actually do not use it for the model. It was just used for testing if the model is able to learn to predict the foreground mask at the very beginning of this project. I will remove it from the code later. Sorry for the confusion!

**Comment by AmirMahdiNassiri** [comment]
@shaohua0116 Thank you so much for the fast reply and the clarification. Your support is greatly appreciated. Wish you the best in your future endeavors.

**Comment by shaohua0116** [comment]
I have removed the foreground mask from the code and done some code cleanup. Thank you!

**Comment by AmirMahdiNassiri** [comment]
I sincerely thank you for actively maintaining the repository
